name: Build AK#Blogroll

on:
  schedule: 
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Clone repo
      shell: bash
      run: git clone -b gh-pages https://github.com/AnzenKodo/AnzenKodo.github.io site
      
    - name: Making Blogroll
      shell: bash
      run: bash src/run.sh --make-blogroll

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site
